name: ShellSpec Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout kcov
        uses: actions/checkout@v4
        with:
          repository: SimonKagstrom/kcov
          path: $HOME/kcov

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake binutils-dev libssl-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev

      - name: Set up ShellSpec
        run: ./setup-action.sh

      - name: Run ShellSpec tests
        run: shellspec -s /bin/bash
