name: ShellSpec Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ShellSpec
        run: ./setup-action.sh

      - name: Run ShellSpec tests
        run: shellspec -s /bin/bash
