name: ShellSpec Test

on:
  push:
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ShellSpec
      run: |        
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        chmod +x shellspec
        sudo mv shellspec /usr/local/bin/

    - name: Run ShellSpec tests
      run: shellspec
